In [1]:
# Using python library to solve the linear equation

In [2]:
import numpy as np

In [5]:
# np.linalg.solve uses LU decomposition to solve the equation

M = np.array([[4,3,8],[-2, -3, 9],[1,0,1]])
b = np.array([2,5,3])

v = np.linalg.solve(M, b)
print(v)

[ 2.93333333 -3.42222222  0.06666667]


In [8]:
# Using matrix inversion and subsequent mat mult to solve the eq

M_inv = np.linalg.inv(M)
w = np.dot(M_inv, b)
print(w)

[ 2.93333333 -3.42222222  0.06666667]


In [14]:
# Using scipy to get the L and U matrices of the decompostion

import scipy as sc
from scipy.linalg import lu

P, L, U = lu(M)

print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
print("The dot product must lead to original matrix:\n", np.dot(L, U))

P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L:
 [[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.25  0.5   1.  ]]
U:
 [[ 4.   3.   8. ]
 [ 0.  -1.5 13. ]
 [ 0.   0.  -7.5]]
The dot product must lead to original matrix:
 [[ 4.  3.  8.]
 [-2. -3.  9.]
 [ 1.  0.  1.]]
