In [1]:
# Inverse Power method

The eigenvalues of the inverse matrix A−1 are the reciprocals of the eigenvalues of A. instead of applying A as
described above, we just apply A−1 for our iteration to find the largest value of λ11 , which will be the
smallest value of the eigenvalues for A

In [2]:
# Finding the smallest eigen value and corresponding eigen vector

In [9]:
import numpy as np
from numpy.linalg import inv

def inv_pwr(inp_vec):
    com_val = abs(inp_vec).max()
    new_vec = inp_vec / inp_vec.max()
    return com_val, new_vec 

In [15]:
M = np.array([[0,5],[1,8]])
M_inv = inv(M)
print(M_inv)
y = np.array([[2],[3]])
store_vec = y
for i in range(10):
    dp = np.dot(M_inv, store_vec)
    least_val, store = inv_pwr(dp)

print("Smallest eigen value:\n",least_val,"and \ncorresponding vector: \n", store)

[[-1.6  1. ]
 [ 0.2  0. ]]
Smallest eigen value:
 0.4 and 
corresponding vector: 
 [[-0.5]
 [ 1. ]]


In [16]:
# The QR method:

The QR method is the preferred iterative method to find all the eigenvalues of a matrix (but not the
eigenvectors at the same time).
 Similar matrices will have the same eigenvalues and associated eigenvectors. Two square matrices A and B are similar if they are connected by similarity transforamtion.

The QR method is a way to decompose a matrix into two matrices Q and R, where Q is
an orthogonal matrix, and R is an upper triangular matrix. An orthogonal matrix satisfies
Q−1 = QT , which means Q−1 Q = QT Q = I

we have qr function in numpy linalg

In [18]:
from numpy.linalg import qr
import numpy as np

In [20]:
arr_a = np.array([[0,2],[2,3]])
q ,r = qr(arr_a)

In [25]:
print("Q: \n", q)
print("R: \n", r)

Q: 
 [[ 0. -1.]
 [-1.  0.]]
R: 
 [[-2. -3.]
 [ 0. -2.]]


In [26]:
d_pro = np.dot(q, r)
d_pro_1 = np.dot(r, q)
print("QR: \n", d_pro)
print("RQ: \n", d_pro_1)

QR: 
 [[0. 2.]
 [2. 3.]]
RQ: 
 [[3. 2.]
 [2. 0.]]


In [70]:
# Get different q and r matrices using successive iteration
# Now using the above qr matrices to get eigen value

Eigen value in qr matrix is on diagonal only when we have upper traingular
matrix as the ddot product r.q. 

In [73]:
arr_b = np.array([[12,3,5],[6,32,1],[3,2,5]])
count = [1, 100, 771, 772, 1000]
store = arr_b
for i in range(1000):     # Number of iteration for qr
    q, r = qr(store)    # setting up q, r matrix formation 
    store = np.dot(r, q)   # taking dot product of decomposed matrices 
    if i+1 in count:       # checking the iteration number and printing if it matches the number in count 
        print("Iteration number: ", i+1)
        print(store)

Iteration number:  1
[[20.71428571  8.96679515 -1.98583068]
 [11.5851039  24.67072671  2.63317367]
 [-0.81000988  0.23277687  3.61498757]]
Iteration number:  100
[[ 3.30693672e+01 -2.47902211e+00 -1.46588147e+00]
 [ 6.33600050e-41  1.25764128e+01 -2.38864834e+00]
 [ 4.91904501e-99 -1.19743235e-57  3.35421996e+00]]
Iteration number:  771
[[ 3.30693672e+001  2.47902211e+000  1.46588147e+000]
 [-1.23516411e-322  1.25764128e+001 -2.38864834e+000]
 [ 0.00000000e+000  0.00000000e+000  3.35421996e+000]]
Iteration number:  772
[[33.06936724 -2.47902211 -1.46588147]
 [ 0.         12.57641281 -2.38864834]
 [ 0.          0.          3.35421996]]
Iteration number:  1000
[[33.06936724 -2.47902211 -1.46588147]
 [ 0.         12.57641281 -2.38864834]
 [ 0.          0.          3.35421996]]


Important poin to note here is, the dot product of qr is changing into
upper triangular matrix at 772nd iteration, therefore we have eigen value on the diagonal only after that iteration

In [40]:
# Using libraries of python to get the eigen values

In [41]:
from numpy.linalg import eig

In [77]:
arr_b = np.array([[12,3,5],[6,32,1],[3,2,5]])
value , vector = eig(arr_b)
print(f"Eigen value is: \n{value}")
print(f"Eigen vector is: \n {vector}" )

Eigen value is: 
[33.06936724 12.57641281  3.35421996]
Eigen vector is: 
 [[-0.16068616 -0.91219811 -0.5194867 ]
 [-0.98314383  0.29634889  0.07910804]
 [-0.08722484 -0.28296987  0.85080873]]
