In [3]:
import numpy as np

In [4]:
z = np.arange(1,1001,1)

In [5]:
z = np.arange(0.5,3,0.5)

In [6]:
# linspace, helps in generation of equally spaced number between starting and end point.
z = np.linspace(2,8,10)
z
# we did not need to assign the interval difference between two numbers

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [7]:
z[4]  #5th element of the array

4.666666666666666

In [8]:
# Multi-dimensional array or matrix generation
m = np.zeros((4,4))
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
n = np.ones((3,2))
n

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# 1-D empty array
a = np.empty(3)
a
# Empty array is not really empty, it is filled iwth very small numbers

array([4.68798154e-310, 0.00000000e+000, 1.58101007e-322])

In [11]:
z = np.arange(1,8,1)
z[3] = 7
z[0] = 1
z[1] = 1
z[2] = 2
z

array([1, 1, 2, 7, 5, 6, 7])

In [12]:
b = np.array([[1,2],[3,4]])
c = np.array([[5,6],[7,8]])
matsum = b+c
matdiff = b-c
matmul = b*c    # this is not our regular MatMul but only element by element multiplication
matsum.shape

(2, 2)

In [20]:
print(b,'\n',c,'\n',matsum,'\n',matdiff,'\n',matmul)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]] 
 [[ 6  8]
 [10 12]] 
 [[-4 -4]
 [-4 -4]] 
 [[ 5 12]
 [21 32]]


In [14]:
z = np.linspace(1,10,20)
z

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [15]:
z>7   

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [16]:
y = np.linspace(5,10,20)

In [17]:
z>y      # element by element comparison of the arrays

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [18]:
w = z[z>6]
w

array([ 6.21052632,  6.68421053,  7.15789474,  7.63157895,  8.10526316,
        8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
# altering the array of z, such that element> 5 will become zero
z[z>5] = 0

In [21]:
matmul.size

4

In [25]:
b = np.zeros((2,2))
b[0,0] = 4
b[0,1] = 2
b[1,0] = 9
b[1,1] = 6
b

array([[4., 2.],
       [9., 6.]])

In [27]:
# Transpose
b.T

array([[4., 9.],
       [2., 6.]])

In [29]:
s = np.sqrt(b)
s

array([[2.        , 1.41421356],
       [3.        , 2.44948974]])