In [289]:
import numpy as np

'''
A recursive function is a function that makes calls to itself. It works like the loops.
Every recursive function has two components: a base case and a recursive step.
'''

In [2]:
# Factorial cal with recursive relation of function
def fun_fact(n):
    if n==1:
        return 1
    else:
        return n*fun_fact(n-1)     # Recurisve Call
fun_fact(4)    

24

In [291]:
# Fibbonacci without recursive
x = 1
y = 1
print(x)
print(y)
sum =0
for i in range(5):
    sum = x + y
    t = x
    x = y
    y = sum
    print(sum)

1
1
2
3
5
8
13


In [292]:
# Fibbonacci with recursive function
def fibbo(n):
    if n == 1:
        return 1
    elif n ==2:
        return 1
    else:
        return fibbo(n-1)+fibbo(n-2)    # recursive call
for i in range(1,8):
    print(fibbo(i))

1
1
2
3
5
8
13


In [293]:
# n fibbonacci numbers
def iter_fibbo(n):
    fib = np.ones(n)     # creating an array with n elements
    print(fib)
    for i in range(2,n):    # Starting from 2, because first and second index are already 1, given in the array
        fib[i] = fib[i-1] + fib[i-2]    # Recursive Call 
    return fib

fibbo_list = iter_fibbo(10)    # exporting the argument and storing the list of fibbo numbers in the given variable    
print(fibbo_list)            
sum = 0
for i in fibbo_list:        # summing up the the n fibbo numbers
    sum = sum + i 
print(sum)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.]
143.0


In [294]:
# It is important for the recursion to reach the base level of recursion

# Tower  of Hanoi problem
'''
The Tower of Hanoi problem consists of three vertical rods (or towers) and N disks of different sizes,
each with a hole in the center so that the rod can slide through it. The original configuration of the disks
is that they are stacked on one of the towers in the order of descending size (i.e., the largest disc is on
the bottom). The goal of the problem is to move all the disks to a different rod while complying with
the following three rules:
1. Only one disk can be moved at a time.
2. Only the disk at the top of a stack may be moved.
3. A disk may not be placed on top of a smaller disk.

The key to the Tower of Hanoi problem is breaking it down into smaller, easier-to-manage problems
that we will refer to as subproblems. For this problem, it is relatively easy to see that moving a disk is
easy (which has only three rules), but moving a tower is difficult, and the solution is not obvious. So
we will assign moving a stack of size N to several subproblems of moving a stack of size N − 1.
Consider a stack of N disks that we wish to move from tower 1 to tower 3, and let my_tower(N)
move a stack of size N to the desired tower (i.e., display the moves). How to write my_tower may not
immediately be clear. If we think about the problem in terms of subproblems, we can see that we need
to move the top N − 1 disks to the middle tower, then the bottom disk to the right tower, and then the
N − 1 disks on the middle tower to the right tower. my_tower can display the instruction to move disk
N and then make recursive calls to my_tower(N-1) to handle moving the smaller towers. The calls to
my_tower(N-1) make recursive calls to my_tower(N-2), and so on.
'''

In [295]:
# Towers of Hanoi Problem
# The program is divided into two set of recursive function program
def towers(N, from_T, to_T, middle_T):
    if N != 0:
# recursive call that moves N-1 stack fro
# starting tower to middle tower        
        towers(N-1, from_T, middle_T, to_T)
        print("moving disc %d from tower %d to tower %d."
              %(N, from_T, to_T))
# recursive call that moves N-1 stack from
# alternate tower to final tower
        towers(N-1, middle_T, to_T, from_T)
towers(3,1,3,2)          

moving disc 1 from tower 1 to tower 3.
moving disc 2 from tower 1 to tower 2.
moving disc 1 from tower 3 to tower 2.
moving disc 3 from tower 1 to tower 3.
moving disc 1 from tower 2 to tower 1.
moving disc 2 from tower 2 to tower 3.
moving disc 1 from tower 1 to tower 3.


In [296]:
# Quicksort, sorting of list, using recursive

def quicksort(lst):
    
    if len(lst) <= 1:
        sorted_list = lst
    else:
        # Selecting pivot as the first element of the list
        pivot = lst[0]
 # creating list for bigger, smaller and same elements as pivot       
        bigger = []
        smaller = []
        same = []
        
        for item in lst:
            if item > pivot:
                bigger.append(item)
            elif item < pivot:
                smaller.append(item)
            else:
                same.append(item)
# Writing the list with the recursive ability of function with bogger and smaller list as argument                 
            sorted_list = quicksort(smaller) + same + quicksort(bigger)
            
    return sorted_list
    
list_a = quicksort([4,2,6,4,23,12,67,90,56,34])
print(list_a)

[2, 4, 4, 6, 12, 23, 34, 56, 67, 90]


In [297]:
# Summing the list elements

def sum_list(list_a):
    sum = 0
    for i in list_a:
        sum += i
    return sum

output1 = sum_list([3,5,7,4,3,75,23,45,87,23,17,58])
output2 = sum_list(range(1,101))
print(output1, output2)

350 5050


In [298]:
# Chebyshev Polynomial
def cheby(n,x):
    y = np.array([])
    if n == 0:
        y = 1
    elif n == 1:
        y = x
    else:
        y = 2*x*cheby(n-1,x) - cheby(n-2,x)
    return y

x = np.array([1,2,3,4,5])

cheby(2,x)

array([ 1,  7, 17, 31, 49])

In [299]:
# Chebyshev Polynomial
def cheby(n,x):
    y = np.array([])
    if n == 0:
        return 1
    elif n == 1:
        return x
    else:
        return 2*x*cheby(n-1,x) - cheby(n-2,x)
    

x = np.array([1,2,3,4,5])

cheby(3,x)

array([  1,  26,  99, 244, 485])

In [300]:
# Ackermann function
# Output is incorrect
def Acker(m,n):
    if m==0:
        return n+1
    elif m>0 and n==1:
        return Acker(m-1, 1)
    else:
        return Acker(m-1, Acker(m, n-1))
    
Acker(1,2)    


3

In [29]:
def triangle(n):
    if n == 0:
        return []
    elif n == 1:
        return [[1]]
    else:
        new_row = [1]          # starting every row with 1
        result = triangle(n-1)    
#Storing all triangles of upto n-1 row such that the can be called in the function       
        last_row = result[-1]     # Calling only the last row of the triangle 
        for i in range(len(last_row)-1):       # running loop over in-between elements,
#such that 1st and last elements (1) is not included
            new_row.append(last_row[i] + last_row[i+1])  
#Since we are counting the 1st element of current row therefore the first element of the loops is actuallysecond
#element of the required row, hence the index 0 of current loop is made up from elements of 0 and 1 of last row.'''
        new_row += [1]      # Adding 1 as the last element to every row list
        result.append(new_row)    
#appending the nth row into the result list of existing n-1 rows of pascal triangle.
#This currently added row can be used as the last row with command result[-1] for next row calculation.'''
    return result

triangle(5)


[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]