In [57]:
# Linear algebra and amd linear equation 

In [84]:
import numpy as np
r_vec = np.array([[1,1,-5,2,7]])
c_vec = np.array([[3],[6],[9],[0]])

print(r_vec.shape)
print(c_vec.shape)

(1, 5)
(4, 1)


In [89]:
# Calculating norm with different method

from numpy.linalg import norm
new_vec = r_vec.T     # Transposing the vector
print(new_vec)

norm1 = norm(new_vec, 1)       # norm = sigma(elements)
norm2 = norm(new_vec, 2)      # norm = sigma(root(square(element)))
norm_inf = norm(new_vec, np.inf)    

print("L_1 is: %.1f"%norm1)
print("L_2 is: %.1f"%norm2)
print("L_inf is: %.1f"%norm_inf)

[[ 1]
 [ 1]
 [-5]
 [ 2]
 [ 7]]
L_1 is: 16.0
L_2 is: 8.9
L_inf is: 7.0


In [90]:
# Vector addition, u(i) = v(i) + w(i)

In [150]:
# The dot-product is a measure of how similarly directed the two vectors are

def dot_pro(m, n):
    for i,j in zip(m,n):
        mult_2 =sum(i*j)
    return mult_2
        
    
vec_1 = np.array([[1,3,1,9]])
vec_2 = np.array([[2,2,7,4]])
dp = dot_pro(vec_1, vec_2)
print(dp)

51


In [158]:
# Dot product with library and finding the respective angle between
# two vectors

from numpy import arccos, dot

v_1 = np.array([[10, 9 ,34, 9]])
v_2 = np.array([[2, 6, 8, 12]])

theta = arccos(dot(v_1, v_2.T)/(norm(v_1)*norm(v_2)))
print(theta)

[[0.69885032]]


In [159]:
# Cross Product

In [164]:
from numpy import cross
v_1 = np.array([[0,2,0]])
v_2 = np.array([[3,0,0]])

print(np.cross(v_1, v_2))
print(np.cross(v_2, v_1))

[[ 0  0 -6]]
[[0 0 6]]


In [178]:
# Matrices
# "np.dot" is used here as well for the matrix multiplication 

In [179]:
from numpy.linalg import det
m_1 = np.array([[0, 2, 1, 3],[3,2,8,1],[1,0,0,3],[0,3,2,1]])
print("m_1:\n",m_1)

print("Determinant: %.1f"%det(m_1))

m_1:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0


In [180]:
I = np.eye(4)
print(np.dot(m_1,I))

[[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [181]:
# Inverse of matrix is: (M)^(-1).M = I
# also, M^(-1) = 1/det(M)*[Cofactor(M)]^(T)

In [182]:
# If determinant of a matrix is zero, then the matrix is singular

In [185]:
from numpy.linalg import inv
print("The matrix is:", m_1)
print("The inverse is:", inv(m_1))

The matrix is: [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
The inverse is: [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [190]:
m_2 = np.array([[0,1,0],[0,0,0],[1,0,1]])
det_m2 = det(m_2)
print(det_m2)

0.0


In [192]:
# The rank of an m × n matrix A is the number of linearly independent columns or rows of A
# and is denoted by rank(A).
# The matrix A is also of full rank if all of its columns are linearly independent.

In [193]:
# An augmented matrix is a matrix A concatenated with a vector y and is written [A, y].
# This is commonly read as “A augmented with y.”

In [213]:
# Finding condition number, rank of matrix
from numpy.linalg import cond, matrix_rank

mat_a = np.array([[1,1,0],[0,1,0],[1,0,1]])

print("The condition number of the matrix a:\n", cond(mat_a))
print("Rank of the matrix a:\n", matrix_rank(mat_a))

The condition number of the matrix a:
 4.048917339522305
Rank of the matrix a:
 3


In [219]:
# Augmented matrix using concatenate library of numpy
mat_b = np.array([[1],[2],[1]])
mat_c = mat_b.T

#adds the the column vector as a new column to already existing one
aug_ab = np.concatenate((mat_a, mat_b), axis = 1)  # axis=1 is for column add

#adds the row vector to the already existing matrix
aug_ac = np.concatenate((mat_a, mat_c), axis = 0) # axis=0 is for row add

print("Augmented matrix of mat a and b:\n", aug_ab)
print("Augmented matrix of mat a and c:\n", aug_ac)

Augmented matrix of mat a and b:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
Augmented matrix of mat a and c:
 [[1 1 0]
 [0 1 0]
 [1 0 1]
 [1 2 1]]


In [223]:
# Checking if the addition of column has increased the rank
# if the rank increases, it would mean the added column is linearly 
# independent vector in the space

print("The rank of augmented matrix ab:\n", matrix_rank(aug_ab))
print("The rank of augmented matrix ac:\n", matrix_rank(aug_ac))

The rank of augmented matrix ab:
 3
The rank of augmented matrix ac:
 3


In [224]:
# Since Rank stays the same, therefore the addition must be linearly dependent vector