In [ ]:
# Linear Transformation

In [ ]:
# Linear independance of an vector wrt to a matrix (set of linear equation)
# is judged by checked by rank(M) and rank of augmented(M,y)
# if rank(aug[M, y]) = rank(M) + 1, then the y is linearly inde wrt
# columns of M.

In [ ]:
# In terms of finding solution with equation M.x = y

Case 1: If M and y happen to be linealy inde, then there can not be any sol of x.

Case 2: There is unique solution: rank(aug[M,y]) = rank(M),
then there is linear dependance y, s.t. it can be written in terms of column vectors of A, solution of x is possible.

In [ ]:
# Gauss Elimination:

x4 can be easily solved for by dividing both sides by a4,4 , and then by substituting the result
into the third equation to solve for x3 . With x3 and x4 , we can substitute them into the second equation
to solve for x2 , and we are now able to solve for all x. We solved the system of equations bottom-up;
this is called backward substitution. Note that, if A were a upper-triangular matrix, we would solve
the system top-down by forward substitution.

Step 1: Turn these equations to the matrix form Ax = y.   
Step 2: Obtain the augmented matrix [A, y]  
Step 3: Start eliminating the elements in the matrix by choosing a pivot equation, which is
used to eliminate the elements in other equations.
step 4: Subsequently try to form a lower-triangular matrix.

Caution: Sometimes the first element in the first row is zero. When this is the case, switch the first row
with a nonzero first element row,

In [ ]:
# Gauss- Jordan elimination method:

Transform the A matrix into identity matrix, s.t. the augmented
matrix with y, would lead to y' values as the solution of x.


In [ ]:
# LU decomposition

The two methods shown above involve changing both A and y at the same time while trying to turn
A to an upper triangular or diagonal matrix form. Sometimes we may have same set of equations but
different sets of y for different experiments. This is actually quite common in the real world, where we
have different experiment observations ya , yb , yc , . . . Therefore, we must solve Ax = ya , Ax = yb , . . .
many times, since every time the [A, y] will change. Obviously, this is really inefficient. Is there a
method by which we only change the left side of A but not the right-hand side y?
The LU decomposition method changes the matrix A only, instead of y. It is ideal for solving the
system with the same coefficient matrices A but different constant vectors y. The LU decomposition
method aims to turn A into the product of two matrices L and U , where L is a lower triangular matrix
while U is an upper triangular matrix

In [4]:
# Programming the Gauss- Elimination:

In [7]:
import numpy as np

n = int(input("Enter the dimension of matrix:"))
mat_a = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        mat_a[[i],[j]] = int(input("Enter the elements of matrix: "))
print(mat_a)

for i in range(n-1):
    for j in range(i,n-1):
        store = mat_a[[i],[i]]/mat_a[[j+1],[i]]
        for k in range(n):
            print(store)
            mat_a[[j+1],[k]] = mat_a[[i],[k]] - mat_a[[j+1],[k]]*store
print(mat_a)

Enter the dimension of matrix:3
Enter the elements of matrix: 1
Enter the elements of matrix: 2
Enter the elements of matrix: 3
Enter the elements of matrix: 4
Enter the elements of matrix: 5
Enter the elements of matrix: 6
Enter the elements of matrix: 7
Enter the elements of matrix: 8
Enter the elements of matrix: 9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[0.25]
[0.25]
[0.25]
[0.14285714]
[0.14285714]
[0.14285714]
[0.875]
[0.875]
[0.875]
[[1.   2.   3.  ]
 [0.   0.75 1.5 ]
 [0.   0.   0.  ]]


In [9]:
# verifying LU decomposition using library

u = np.array([[4, 3, 5],[0, -2.5, 2.5],[0, 0, 12]])
l = np.array([[1, 0, 0],[-0.5, 1, 0],[2, -0.8, 1]])

print("LU =", np.dot(l, u))

LU = [[ 4.  3.  5.]
 [-2. -4.  0.]
 [ 8.  8. 20.]]
